# -*- coding: utf-8 -*-
"""abattia_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/abattiasia/cf2d561ae43f0c0f4ecaea7952143b9f/abattia_exercise.ipynb
"""



"""**Exercise 01**"""

name= "Abdou Attia"
age= 64
print (name , age)

"""Exercise 02"""

a= 15
b= 5
print (a+b)
print (a-b)
print (a*b)
print (a**b)

"""Exercise 03"""

first_name = "Abdou"
last_name= "Attia"
print (first_name + " "+ last_name)



"""Exercise 04"""

counter=4
counter=counter+1
print (counter)



"""Exercise 05"""

x = 6
y = 7
print ("x, y = ", x,y)
z = y
y = x
x=z
print ("x, y = ",x,y)

"""Exercise 06

"""

PI=3.14159
radius= 5
circumference = 2*PI*radius
print("circumference = ", circumference)

"""Exercise 07"""

is_sunny= True
is_raining= False
print (is_sunny, is_raining)